# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Test

on: [push, pull_request]

jobs:
  test-suntori:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test Fetcher
        working-directory: ./Fetcher
        run: npm ci --quiet --no-progress && npm test

      - name: Test HtmlParser.
        working-directory: ./HtmlParser
        run: npm ci --quiet --no-progress && npm test

      - name: Test Types
        working-directory: ./Types
        run: npm ci --quiet --no-progress && npm test

      - name: Test Utils
        working-directory: ./Utils
        run: npm ci --quiet --no-progress && npm test

      - name: Test Yunomix
        working-directory: ./Yunomix
        run: npm ci --quiet --no-progress && npm test
